name: 'Deploy Flutter web app to github pages'
description: 'Automates the build and deployment of your Flutter web app on Github gh pages'
author: 'WilliamKarolDiCioccio'

branding:
  color: "green"
  icon: "globe"

inputs:
  webRenderer:
    description: 'Which web renderer to be used, default is auto'
    required: false
    default: "auto"
  compileToWasm:
    description: "Compile to wasm, if used this will ignore the webRenderer flag, default is false"
    required: false
    default: "false"
  workingDir:
    description: 'The directory where the project is (default .)'
    required: false
    default: "."
  targetBranch:
    description: 'The branch where the build artifacts will be pushed'
    required: false
    default: "gh-pages"
  baseHref:
    description: 'base href (if applicable)'
    required: false
    default: "/"
  customArgs:
    description: 'Custom args like: --dart-define="simple=example"'
    required: false

runs:
  using: 'composite'
  steps:
    # Set the "flutter_version" environment variable for later use
    - run: echo "flutter_version=$(flutter --version | awk '{print $2}' | tr -dc '0-9')" >> $GITHUB_ENV
      shell: bash

    # Enable web support
    - run: flutter config --enable-web
      shell: bash
      working-directory: ${{inputs.workingDir}}

    # Build with the default options for Flutter >= 3.29.0 or when webRenderer is auto
    - run: flutter build web --release --base-href ${{ inputs.baseHref }} ${{ inputs.customArgs }}
      if: ${{ inputs.compileToWasm == 'false' && (inputs.webRenderer == 'auto' || env.flutter_version >= 3290) }}
      shell: bash
      working-directory: ${{ inputs.workingDir }}

    # Ignore --web-render argument for flutter >= 3.29.0 and above
    - run: flutter build web --release --web-renderer=${{inputs.webRenderer}} --base-href ${{inputs.baseHref}} ${{inputs.customArgs}}
      if: ${{ env.flutter_version < 3290 && inputs.compileToWasm == 'false' && inputs.webRenderer != 'auto' }}
      shell: bash
      working-directory: ${{inputs.workingDir}}
      
    # Ignore --wasm argument for flutter < 3.24.0 and below
    - run: flutter build web --release --wasm --base-href ${{inputs.baseHref}} ${{inputs.customArgs}}
      if: ${{ env.flutter_version >= 3240 && inputs.compileToWasm == 'true' }}
      shell: bash
      working-directory: ${{inputs.workingDir}}

    # Authenticate as the GitHub Actions bot in the git CLI
    - run: git config user.name github-actions
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git config user.email github-actions@github.com
      shell: bash
      working-directory: ${{inputs.workingDir}}

    # Add all changes to the git index
    - run: git --work-tree build/web add --all
      shell: bash
      working-directory: ${{inputs.workingDir}}
    
    # Commit the changes
    - run: git commit -m "Automatic deployment by github-actions" # Cannot fail beacuse there are always changes in the build/web folder
      shell: bash
      working-directory: ${{inputs.workingDir}}

    # Push the changes
    - run: git push origin HEAD:${{inputs.targetBranch}} --force
      shell: bash
      working-directory: ${{inputs.workingDir}}